base_images:
  base:
    name: "4.4"
    namespace: ocp
    tag: base
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.14
images:
  - dockerfile_path: deploy/Dockerfile
    from: base
    to: aws-account-shredder
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
zz_generated_metadata:
  branch: master
  org: openshift
  repo: aws-account-shredder
